version: '3.5'
services:
  app:
    build: .
    volumes:
      - .:/usr/app
    ports:
      - '8080:8080'
      - '1337:1337'
    depends_on:
      - pg
    environment:
      NODE_ENV: "development"
      SEQUELIZE_USER: "andrewyan"
      SEQUELIZE_PASSWORD: "123456"
      SEQUELIZE_DB: "mydb_development"
      SEQUELIZE_HOST: "pg"
    entrypoint: /bin/sh
    tty: true
    stdin_open: true
  pg:
    image: postgres:10.2-alpine
    volumes:
      - ./pgdata-development:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "andrewyan"
      POSTGRES_DB: "mydb_development"
  pg_test:
    image: postgres:10.2-alpine
    volumes:
      - ./pgdata-test:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "andrewyan"
      POSTGRES_DB: "mydb_test"
  nginx:
    build:
      context: ./nginx/dev
      dockerfile: Dockerfile
    ports:
      - "80:80"
