version: '3.5'
services:
  app:
    build: .
    volumes:
      - .:/usr/app
    ports:
      - '8080:8080'
      - '1337:1337'
    depends_on:
      - pg
    command: yarn run dev
  pg:
    image: postgres:10.2-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "andrewyan"
      POSTGRES_DB: "mydb_development"
