apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddn
  labels:
    app: ddn
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: ddn
  template:
    metadata:
      labels:
        apps: ddn
    spec:
      containers:
        - name: ddn
          image: ddn:latest
          imagePullPolicy: Never
          command: 
            - tail
          args:
            - "-f"
            - "/dev/null"
          env:
            - name: NODE_ENV
              value: development
            - name: SEQUELIZE_USER
              value: andrewyan
            - name: SEQUELIZE_PASSWORD
              value: "123456"
            - name: SEQUELIZE_DB
              value: mydb_development
            - name: SEQUELIZE_HOST
              value: "127.0.0.1"
          ports:
            - containerPort: 8080
            - containerPort: 1337
          volumeMounts:
            - name: code
              mountPath: /usr/app
        - name: pg
          image: postgres:10.2-alpine
          env:
            - name: POSTGRES_USER
              value: andrewyan
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: POSTGRES_DB
              value: mydb_development
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pg
              mountPath: /usr/pg
        - name: pg-test
          image: postgres:10.2-alpine
          env:
            - name: POSTGRES_USER
              value: andrewyan
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: POSTGRES_DB
              value: mydb_test
            - name: PGPORT
              value: "5433"
          ports:
            - containerPort: 5433
          volumeMounts:
            - name: pg-test
              mountPath: /usr/pg-test
        - name: nginx
          image: nginx:1.13.8-alpine
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
            - name: nginx-crt
              mountPath: /etc/ssl/certs/nginx-selfsigned.crt
            - name: nginx-key
              mountPath: /etc/ssl/certs/nginx-selfsigned.key
      volumes:
        - name: code
          hostPath:
            path: /Users/zushenyan/Documents/github/deploy-docker-node
        - name: pg
          hostPath:
            path: /Users/zushenyan/Documents/github/deploy-docker-node/pgdata-development
        - name: pg-test
          hostPath:
            path: /Users/zushenyan/Documents/github/deploy-docker-node/pgdata-test
        - name: nginx-config
          hostPath:
            path: /Users/zushenyan/Documents/github/deploy-docker-node/nginx/dev/nginx.conf
        - name: nginx-crt
          hostPath:
            path: /Users/zushenyan/Documents/github/deploy-docker-node/nginx/dev/nginx-selfsigned.crt
        - name: nginx-key
          hostPath:
            path: /Users/zushenyan/Documents/github/deploy-docker-node/nginx/dev/nginx-selfsigned.key
---
apiVersion: v1
kind: Service
metadata:
  name: ddn
  labels:
    app: ddn
spec:
  selector:
    apps: ddn
  type: NodePort
  ports:
    - name: app-port
      port: 8080
      nodePort: 30005
    - name: app-debug-port
      port: 1337
      nodePort: 30006
    - name: nginx-http
      port: 80
      nodePort: 30007
    - name: nginx-https
      port: 443
      nodePort: 30008