apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-data
spec:
  storageClassName: my-pg
  capacity:
    storage:  2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/pg-data/