apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ddn:latest
          imagePullPolicy: Never
          command:
            - yarn
          args:
            - run
            - seed
          env:
            - name: NODE_PATH
              value: "."
            - name: NODE_ENV
              value: production
            - name: SEQUELIZE_USER
              value: andrewyan
            - name: SEQUELIZE_PASSWORD
              value: "123456"
            - name: SEQUELIZE_DB
              value: mydb_production
            - name: SEQUELIZE_HOST
              value: "pg-service.default"