apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.13.8-alpine
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx
            - name: nginx-ssl
              mountPath: /etc/ssl/certs
          
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-conf
        - name: nginx-ssl
          secret:
            secretName: nginx-ssl
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - name: nginx-http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: nginx-https
      port: 443
      targetPort: 443
      protocol: TCP
