apiVersion: apps/v1
kind: Deployment
metadata:
  name: job
spec:
  selector:
    matchLabels:
      app: job
  replicas: 1
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
        - name: app
          image: ddn:latest
          imagePullPolicy: Never
          env:
            - name: NODE_ENV
              value: production
            - name: SEQUELIZE_USER
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: pg-user
            - name: SEQUELIZE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: pg-password
            - name: SEQUELIZE_DB
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: pg-db
            - name: SEQUELIZE_HOST
              value: "pg-service.default"